version: '3.8'
services:
  db:
    image: postgres:16
    container_name: ramene-db
    environment:
      POSTGRES_DB: ramene_talaine
      POSTGRES_USER: ramene_admin
      POSTGRES_PASSWORD: ChangeMe123!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: