spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/ramene_talaine}
spring.datasource.username=${JDBC_DATABASE_USERNAME:ramene_admin}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:ChangeMe123!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
